package com.zzk.bean;
// Generated 2016-3-23 22:10:38 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * M01StStbprpB generated by hbm2java
 */
public class M01StStbprpB implements java.io.Serializable {

	private String stcd;
	private String stnm;
	private String rvnm;
	private String hnnm;
	private String bsnm;
	private Double lgtd;
	private Double lttd;
	private String stlc;
	private String addvcd;
	private BigDecimal mdbz;
	private BigDecimal mdpr;
	private String dtmnm;
	private BigDecimal dtmel;
	private String sttp;
	private Byte dfrtms;
	private String fritm;
	private Character frgrd;
	private String bgfrym;
	private String edfrym;
	private String admauth;
	private Character stbk;
	private Integer drna;
	private String phcd;
	private Short zhhsDisplayMap;
	private Boolean isimportant;
	private BigDecimal jgsw;
	private BigDecimal bzsw;

	public M01StStbprpB() {
	}

	public M01StStbprpB(String stcd, String stnm, String addvcd, String sttp,
			String admauth) {
		this.stcd = stcd;
		this.stnm = stnm;
		this.addvcd = addvcd;
		this.sttp = sttp;
		this.admauth = admauth;
	}

	public M01StStbprpB(String stcd, String stnm, String rvnm, String hnnm,
			String bsnm, Double lgtd, Double lttd, String stlc, String addvcd,
			BigDecimal mdbz, BigDecimal mdpr, String dtmnm, BigDecimal dtmel,
			String sttp, Byte dfrtms, String fritm, Character frgrd,
			String bgfrym, String edfrym, String admauth, Character stbk,
			Integer drna, String phcd, Short zhhsDisplayMap,
			Boolean isimportant, BigDecimal jgsw, BigDecimal bzsw) {
		this.stcd = stcd;
		this.stnm = stnm;
		this.rvnm = rvnm;
		this.hnnm = hnnm;
		this.bsnm = bsnm;
		this.lgtd = lgtd;
		this.lttd = lttd;
		this.stlc = stlc;
		this.addvcd = addvcd;
		this.mdbz = mdbz;
		this.mdpr = mdpr;
		this.dtmnm = dtmnm;
		this.dtmel = dtmel;
		this.sttp = sttp;
		this.dfrtms = dfrtms;
		this.fritm = fritm;
		this.frgrd = frgrd;
		this.bgfrym = bgfrym;
		this.edfrym = edfrym;
		this.admauth = admauth;
		this.stbk = stbk;
		this.drna = drna;
		this.phcd = phcd;
		this.zhhsDisplayMap = zhhsDisplayMap;
		this.isimportant = isimportant;
		this.jgsw = jgsw;
		this.bzsw = bzsw;
	}

	public String getStcd() {
		return this.stcd;
	}

	public void setStcd(String stcd) {
		this.stcd = stcd;
	}

	public String getStnm() {
		return this.stnm;
	}

	public void setStnm(String stnm) {
		this.stnm = stnm;
	}

	public String getRvnm() {
		return this.rvnm;
	}

	public void setRvnm(String rvnm) {
		this.rvnm = rvnm;
	}

	public String getHnnm() {
		return this.hnnm;
	}

	public void setHnnm(String hnnm) {
		this.hnnm = hnnm;
	}

	public String getBsnm() {
		return this.bsnm;
	}

	public void setBsnm(String bsnm) {
		this.bsnm = bsnm;
	}

	public Double getLgtd() {
		return this.lgtd;
	}

	public void setLgtd(Double lgtd) {
		this.lgtd = lgtd;
	}

	public Double getLttd() {
		return this.lttd;
	}

	public void setLttd(Double lttd) {
		this.lttd = lttd;
	}

	public String getStlc() {
		return this.stlc;
	}

	public void setStlc(String stlc) {
		this.stlc = stlc;
	}

	public String getAddvcd() {
		return this.addvcd;
	}

	public void setAddvcd(String addvcd) {
		this.addvcd = addvcd;
	}

	public BigDecimal getMdbz() {
		return this.mdbz;
	}

	public void setMdbz(BigDecimal mdbz) {
		this.mdbz = mdbz;
	}

	public BigDecimal getMdpr() {
		return this.mdpr;
	}

	public void setMdpr(BigDecimal mdpr) {
		this.mdpr = mdpr;
	}

	public String getDtmnm() {
		return this.dtmnm;
	}

	public void setDtmnm(String dtmnm) {
		this.dtmnm = dtmnm;
	}

	public BigDecimal getDtmel() {
		return this.dtmel;
	}

	public void setDtmel(BigDecimal dtmel) {
		this.dtmel = dtmel;
	}

	public String getSttp() {
		return this.sttp;
	}

	public void setSttp(String sttp) {
		this.sttp = sttp;
	}

	public Byte getDfrtms() {
		return this.dfrtms;
	}

	public void setDfrtms(Byte dfrtms) {
		this.dfrtms = dfrtms;
	}

	public String getFritm() {
		return this.fritm;
	}

	public void setFritm(String fritm) {
		this.fritm = fritm;
	}

	public Character getFrgrd() {
		return this.frgrd;
	}

	public void setFrgrd(Character frgrd) {
		this.frgrd = frgrd;
	}

	public String getBgfrym() {
		return this.bgfrym;
	}

	public void setBgfrym(String bgfrym) {
		this.bgfrym = bgfrym;
	}

	public String getEdfrym() {
		return this.edfrym;
	}

	public void setEdfrym(String edfrym) {
		this.edfrym = edfrym;
	}

	public String getAdmauth() {
		return this.admauth;
	}

	public void setAdmauth(String admauth) {
		this.admauth = admauth;
	}

	public Character getStbk() {
		return this.stbk;
	}

	public void setStbk(Character stbk) {
		this.stbk = stbk;
	}

	public Integer getDrna() {
		return this.drna;
	}

	public void setDrna(Integer drna) {
		this.drna = drna;
	}

	public String getPhcd() {
		return this.phcd;
	}

	public void setPhcd(String phcd) {
		this.phcd = phcd;
	}

	public Short getZhhsDisplayMap() {
		return this.zhhsDisplayMap;
	}

	public void setZhhsDisplayMap(Short zhhsDisplayMap) {
		this.zhhsDisplayMap = zhhsDisplayMap;
	}

	public Boolean getIsimportant() {
		return this.isimportant;
	}

	public void setIsimportant(Boolean isimportant) {
		this.isimportant = isimportant;
	}

	public BigDecimal getJgsw() {
		return this.jgsw;
	}

	public void setJgsw(BigDecimal jgsw) {
		this.jgsw = jgsw;
	}

	public BigDecimal getBzsw() {
		return this.bzsw;
	}

	public void setBzsw(BigDecimal bzsw) {
		this.bzsw = bzsw;
	}

}
