package com.zzk.bean;
// Generated 2016-3-23 22:10:38 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * M02StRsvrR0 generated by hbm2java
 */
public class M02StRsvrR0 implements java.io.Serializable {

	private int id;
	private String stcd;
	private Date tm;
	private BigDecimal rz;
	private BigDecimal inq;
	private BigDecimal w;
	private BigDecimal otq;
	private Character rwchrcd;
	private Character rwptn;
	private BigDecimal inqdr;
	private Character msqmt;
	private Character err;
	private String tstcd;

	public M02StRsvrR0() {
	}

	public M02StRsvrR0(int id, String stcd, Date tm) {
		this.id = id;
		this.stcd = stcd;
		this.tm = tm;
	}

	public M02StRsvrR0(int id, String stcd, Date tm, BigDecimal rz,
			BigDecimal inq, BigDecimal w, BigDecimal otq, Character rwchrcd,
			Character rwptn, BigDecimal inqdr, Character msqmt, Character err,
			String tstcd) {
		this.id = id;
		this.stcd = stcd;
		this.tm = tm;
		this.rz = rz;
		this.inq = inq;
		this.w = w;
		this.otq = otq;
		this.rwchrcd = rwchrcd;
		this.rwptn = rwptn;
		this.inqdr = inqdr;
		this.msqmt = msqmt;
		this.err = err;
		this.tstcd = tstcd;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStcd() {
		return this.stcd;
	}

	public void setStcd(String stcd) {
		this.stcd = stcd;
	}

	public Date getTm() {
		return this.tm;
	}

	public void setTm(Date tm) {
		this.tm = tm;
	}

	public BigDecimal getRz() {
		return this.rz;
	}

	public void setRz(BigDecimal rz) {
		this.rz = rz;
	}

	public BigDecimal getInq() {
		return this.inq;
	}

	public void setInq(BigDecimal inq) {
		this.inq = inq;
	}

	public BigDecimal getW() {
		return this.w;
	}

	public void setW(BigDecimal w) {
		this.w = w;
	}

	public BigDecimal getOtq() {
		return this.otq;
	}

	public void setOtq(BigDecimal otq) {
		this.otq = otq;
	}

	public Character getRwchrcd() {
		return this.rwchrcd;
	}

	public void setRwchrcd(Character rwchrcd) {
		this.rwchrcd = rwchrcd;
	}

	public Character getRwptn() {
		return this.rwptn;
	}

	public void setRwptn(Character rwptn) {
		this.rwptn = rwptn;
	}

	public BigDecimal getInqdr() {
		return this.inqdr;
	}

	public void setInqdr(BigDecimal inqdr) {
		this.inqdr = inqdr;
	}

	public Character getMsqmt() {
		return this.msqmt;
	}

	public void setMsqmt(Character msqmt) {
		this.msqmt = msqmt;
	}

	public Character getErr() {
		return this.err;
	}

	public void setErr(Character err) {
		this.err = err;
	}

	public String getTstcd() {
		return this.tstcd;
	}

	public void setTstcd(String tstcd) {
		this.tstcd = tstcd;
	}

}
