package com.zzk.bean;
// Generated 2016-3-23 22:10:38 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * M02StPptnR0 generated by hbm2java
 */
public class M02StPptnR0 implements java.io.Serializable {

	private int id;
	private String stcd;
	private Date tm;
	private BigDecimal val;
	private BigDecimal subVal;
	private char err;
	private String tstcd;

	public M02StPptnR0() {
	}

	public M02StPptnR0(int id, String stcd, Date tm, BigDecimal val,
			BigDecimal subVal, char err) {
		this.id = id;
		this.stcd = stcd;
		this.tm = tm;
		this.val = val;
		this.subVal = subVal;
		this.err = err;
	}

	public M02StPptnR0(int id, String stcd, Date tm, BigDecimal val,
			BigDecimal subVal, char err, String tstcd) {
		this.id = id;
		this.stcd = stcd;
		this.tm = tm;
		this.val = val;
		this.subVal = subVal;
		this.err = err;
		this.tstcd = tstcd;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStcd() {
		return this.stcd;
	}

	public void setStcd(String stcd) {
		this.stcd = stcd;
	}

	public Date getTm() {
		return this.tm;
	}

	public void setTm(Date tm) {
		this.tm = tm;
	}

	public BigDecimal getVal() {
		return this.val;
	}

	public void setVal(BigDecimal val) {
		this.val = val;
	}

	public BigDecimal getSubVal() {
		return this.subVal;
	}

	public void setSubVal(BigDecimal subVal) {
		this.subVal = subVal;
	}

	public char getErr() {
		return this.err;
	}

	public void setErr(char err) {
		this.err = err;
	}

	public String getTstcd() {
		return this.tstcd;
	}

	public void setTstcd(String tstcd) {
		this.tstcd = tstcd;
	}

}
