package com.zzk.bean;
// Generated 2016-3-23 22:10:38 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * M02StRiverR0 generated by hbm2java
 */
public class M02StRiverR0 implements java.io.Serializable {

	private int id;
	private String stcd;
	private Date tm;
	private BigDecimal z;
	private BigDecimal q;
	private BigDecimal xsa;
	private BigDecimal xsavv;
	private BigDecimal xsmxv;
	private Character flwchrcd;
	private Character wptn;
	private Character msqmt;
	private Character msamt;
	private Character msvmt;
	private Character err;
	private String tstcd;

	public M02StRiverR0() {
	}

	public M02StRiverR0(int id, String stcd, Date tm) {
		this.id = id;
		this.stcd = stcd;
		this.tm = tm;
	}

	public M02StRiverR0(int id, String stcd, Date tm, BigDecimal z,
			BigDecimal q, BigDecimal xsa, BigDecimal xsavv, BigDecimal xsmxv,
			Character flwchrcd, Character wptn, Character msqmt,
			Character msamt, Character msvmt, Character err, String tstcd) {
		this.id = id;
		this.stcd = stcd;
		this.tm = tm;
		this.z = z;
		this.q = q;
		this.xsa = xsa;
		this.xsavv = xsavv;
		this.xsmxv = xsmxv;
		this.flwchrcd = flwchrcd;
		this.wptn = wptn;
		this.msqmt = msqmt;
		this.msamt = msamt;
		this.msvmt = msvmt;
		this.err = err;
		this.tstcd = tstcd;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStcd() {
		return this.stcd;
	}

	public void setStcd(String stcd) {
		this.stcd = stcd;
	}

	public Date getTm() {
		return this.tm;
	}

	public void setTm(Date tm) {
		this.tm = tm;
	}

	public BigDecimal getZ() {
		return this.z;
	}

	public void setZ(BigDecimal z) {
		this.z = z;
	}

	public BigDecimal getQ() {
		return this.q;
	}

	public void setQ(BigDecimal q) {
		this.q = q;
	}

	public BigDecimal getXsa() {
		return this.xsa;
	}

	public void setXsa(BigDecimal xsa) {
		this.xsa = xsa;
	}

	public BigDecimal getXsavv() {
		return this.xsavv;
	}

	public void setXsavv(BigDecimal xsavv) {
		this.xsavv = xsavv;
	}

	public BigDecimal getXsmxv() {
		return this.xsmxv;
	}

	public void setXsmxv(BigDecimal xsmxv) {
		this.xsmxv = xsmxv;
	}

	public Character getFlwchrcd() {
		return this.flwchrcd;
	}

	public void setFlwchrcd(Character flwchrcd) {
		this.flwchrcd = flwchrcd;
	}

	public Character getWptn() {
		return this.wptn;
	}

	public void setWptn(Character wptn) {
		this.wptn = wptn;
	}

	public Character getMsqmt() {
		return this.msqmt;
	}

	public void setMsqmt(Character msqmt) {
		this.msqmt = msqmt;
	}

	public Character getMsamt() {
		return this.msamt;
	}

	public void setMsamt(Character msamt) {
		this.msamt = msamt;
	}

	public Character getMsvmt() {
		return this.msvmt;
	}

	public void setMsvmt(Character msvmt) {
		this.msvmt = msvmt;
	}

	public Character getErr() {
		return this.err;
	}

	public void setErr(Character err) {
		this.err = err;
	}

	public String getTstcd() {
		return this.tstcd;
	}

	public void setTstcd(String tstcd) {
		this.tstcd = tstcd;
	}

}
